### ISSUE TITLE
Needs a License

### ISSUE THREAD

**Issue by anonfunc** [thepauleh/goserverless#8]
Currently, the allowed uses of this library are unclear.

Thank you!

**Comment by Paul-PSDigital** [comment]
Hi Dwight, not sure which one it would be but essentially 'use it however you like, i take no responsibility or impose any restrictions'. I've sent you a collab invite to make any other changes you feel are necessary on this project (i'm not coding at the moment), thanks for your assistance so far keeping this project up to date!

**Comment by anonfunc** [comment]
Sounds like basic MIT license, then.  I'll add it and merge my other PR.

Thank you for writing it, it's a great extension of the goformation idea!
